---
- hosts: all
  collections:
  - redhat.rhel_system_roles
  roles:
  - role: redhat.rhel_system_roles.selinux
  tasks:
    - name: Enable SELinux
      selinux:
        policy: targeted
        state: enforcing
      become: true
